[package]
name = "safecoin-bpf-rust-noop"
version = "0.1.0"
description = "Safecoin BPF noop program written in Rust"
authors = ["Safecoin Maintainers <maintainers@safecoin.org>"]
repository = "https://github.com/solana-labs/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
edition = "2018"

[dependencies]
num-derive = "0.2"
num-traits = "0.2"
solana-program = "1.4.16"
thiserror = "1.0"

[workspace]
members = []

[lib]
name = "safecoin_bpf_rust_noop"
crate-type = ["cdylib"]
