[package]
name = "solana-transaction-pool"
version = "1.11.0"
description = "Solana transaction pool"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-transaction-pool"
edition = "2021"

[dependencies]
log = "0.4.14"
solana-frozen-abi = { path = "../frozen-abi", version = "=1.11.0" }
solana-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.11.0" }
solana-sdk = { path = "../sdk", version = "=1.11.0" }
rand = "0.7.0"

[lib]
crate-type = ["lib"]
name = "solana_transaction_pool"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"

[[bench]]
name = "pool"
