[package]
name = "solana-client"
description = "Solana Client"
documentation = "https://docs.rs/solana-client"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
log = "0.4.17"
solana-measure = { path = "../measure", version = "=1.15.0" }
solana-pubsub-client = { path = "../pubsub-client", version = "=1.15.0" }
solana-rpc-client = { path = "../rpc-client", version = "=1.15.0" }
solana-rpc-client-api = { path = "../rpc-client-api", version = "=1.15.0" }
solana-rpc-client-nonce-utils = { path = "../rpc-client-nonce-utils", version = "=1.15.0" }
solana-sdk = { path = "../sdk", version = "=1.15.0" }
solana-thin-client = { path = "../thin-client", version = "=1.15.0" }
solana-tpu-client = { path = "../tpu-client", version = "=1.15.0" }

[dev-dependencies]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
