[package]
name = "solana-config-program"
description = "Solana Config program"
documentation = "https://docs.rs/solana-config-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = "1.3.3"
chrono = { version = "0.4.22", features = ["serde"] }
serde = "1.0.144"
serde_derive = "1.0.103"
solana-program-runtime = { path = "../../program-runtime", version = "=1.15.0" }
solana-sdk = { path = "../../sdk", version = "=1.15.0" }

[dev-dependencies]
solana-logger = { path = "../../logger", version = "=1.15.0" }

[lib]
crate-type = ["lib"]
name = "solana_config_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
