[package]
name = "safecoin-config-program"
version = "1.6.0"
description = "Safecoin Config program"
authors = ["Safecoin Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
edition = "2018"

[dependencies]
bincode = "1.3.1"
chrono = { version = "0.4.11", features = ["serde"] }
log = "0.4.11"
serde = "1.0.122"
serde_derive = "1.0.103"
safecoin-sdk = { path = "../../sdk", version = "1.6.0" }

[dev-dependencies]
safecoin-logger = { path = "../../logger", version = "1.6.0" }

[lib]
crate-type = ["lib"]
name = "safecoin_config_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
