[package]
name = "safecoin-cargo-build-bpf"
version = "1.6.0"
description = "Compile a local package and all of its dependencies using the Safecoin BPF SDK"
authors = ["Safecoin Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/safecoin"
homepage = "https://safecoin.org/"
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
clap = "2.33.3"
cargo_metadata = "0.12.0"
safecoin-sdk = { path = "..", version = "1.6.0" }

[features]
program = []

[[bin]]
name = "cargo-build-bpf"
path = "src/main.rs"
