[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-remote-wallet"
description = "Blockchain, Rebuilt for Scale"
version = "0.24.0"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
base32 = "0.4.0"
dialoguer = "0.5.0"
hidapi = "1.1.1"
log = "0.4.8"
parking_lot = "0.7"
rusb = "0.5.5"
semver = "0.9"
solana-sdk = { path = "../sdk", version = "0.24.0" }
thiserror = "1.0"

[dev-dependencies]
