[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-transaction-runner"
description = "The solana transaction runner"
version = "1.16.0"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-scheduler"
publish = true

[dependencies]
solana-sdk = { path = "../sdk", version = "=1.16.0" }

[lib]
crate-type = ["lib"]
name = "solana_transaction_runner"
