[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-transaction-runner"
description = "The solana transaction runner"
version = "1.16.0"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-scheduler"
publish = true

[dependencies]
cpu-time = "1.0.0"
crossbeam-channel = "0.5"
log = "0.4.17"
solana-ledger = { path = "../ledger", version = "=1.16.0" }
solana-metrics = { path = "../metrics", version = "=1.16.0" }
solana-poh = { path = "../poh", version = "=1.16.0" }
solana-program-runtime = { path = "../program-runtime", version = "=1.16.0" }
solana-runtime = { path = "../runtime", version = "=1.16.0" }
solana-scheduler = { path = "../scheduler", version = "=1.16.0" }
solana-sdk = { path = "../sdk", version = "=1.16.0" }
thread-priority = "0.9.2"
variant_counter = "0.4.0"

[lib]
crate-type = ["lib"]
name = "solana_transaction_runner"
