[package]
name = "safecoin-vest-program"
version = "1.6.0"
description = "Safecoin Vest program"
authors = ["Safecoin Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
edition = "2018"

[dependencies]
bincode = "1.3.1"
chrono = { version = "0.4.11", features = ["serde"] }
num-derive = "0.3"
num-traits = "0.2"
serde = "1.0.122"
serde_derive = "1.0.103"
safecoin-sdk = { path = "../../sdk", version = "1.6.0" }
safecoin-config-program = { path = "../config", version = "1.6.0" }
thiserror = "1.0"

[dev-dependencies]
safecoin-runtime = { path = "../../runtime", version = "1.6.0" }

[lib]
crate-type = ["lib"]
name = "safecoin_vest_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
