[package]
name = "gen-headers"
publish = false
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
log = { version = "0.4.17", features = ["std"] }
regex = "1.6.0"

[[bin]]
name = "gen-headers"
path = "src/main.rs"
