[package]
authors = ["Safecoin Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "safecoin-local-cluster"
description = "Blockchain, Rebuilt for Scale"
version = "1.6.0"
repository = "https://github.com/solana-labs/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"

[dependencies]
crossbeam-channel = "0.4"
itertools = "0.9.0"
gag = "0.1.10"
fs_extra = "1.1.0"
log = "0.4.11"
rand = "0.7.0"
safecoin-config-program = { path = "../programs/config", version = "1.6.0" }
safecoin-core = { path = "../core", version = "1.6.0" }
safecoin-client = { path = "../client", version = "1.6.0" }
safecoin-download-utils = { path = "../download-utils", version = "1.6.0" }
safecoin-faucet = { path = "../faucet", version = "1.6.0" }
safecoin-exchange-program = { path = "../programs/exchange", version = "1.6.0" }
safecoin-ledger = { path = "../ledger", version = "1.6.0" }
safecoin-logger = { path = "../logger", version = "1.6.0" }
safecoin-runtime = { path = "../runtime", version = "1.6.0" }
safecoin-sdk = { path = "../sdk", version = "1.6.0" }
safecoin-stake-program = { path = "../programs/stake", version = "1.6.0" }
safecoin-vest-program = { path = "../programs/vest", version = "1.6.0" }
safecoin-vote-program = { path = "../programs/vote", version = "1.6.0" }
tempfile = "3.1.0"
safecoin-rayon-threadlimit = { path = "../rayon-threadlimit", version = "1.6.0" }

[dev-dependencies]
assert_matches = "1.3.0"
serial_test = "0.4.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
