[package]
name = "solana-stake-tests"
version = "0.21.1"
description = "Solana stake tests"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
log = "0.4.8"
solana-logger = { path = "../../logger", version = "0.21.1" }
solana-sdk = { path = "../../sdk", version = "0.21.1" }
solana-stake-program = { path = "../stake", version = "0.21.1" }
solana-vote-program = { path = "../vote", version = "0.21.1" }

[dev-dependencies]
solana-runtime = { path = "../../runtime", version = "0.21.1" }
assert_matches = "1.3.0"
