[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "solana-cli-output"
description = "Blockchain, Rebuilt for Scale"
version = "1.2.32"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
chrono = { version = "0.4.11", features = ["serde"] }
console = "0.10.1"
humantime = "2.0.0"
Inflector = "0.11.4"
indicatif = "0.14.0"
serde = "1.0.110"
serde_derive = "1.0.103"
serde_json = "1.0.53"
solana-clap-utils = { path = "../clap-utils", version = "1.2.32" }
solana-client = { path = "../client", version = "1.2.32" }
solana-sdk = { path = "../sdk", version = "1.2.32" }
solana-stake-program = { path = "../programs/stake", version = "1.2.32" }
solana-transaction-status = { path = "../transaction-status", version = "1.2.32" }
solana-vote-program = { path = "../programs/vote", version = "1.2.32" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
