[package]
name = "solana-register"
version = "0.17.0"
description = "Solana validator registration tool"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[features]
cuda = []


[dependencies]
bincode = "1.1.4"
clap = "2.33"
dirs = "2.0.1"
solana-client = { path = "../client", version = "0.17.0" }
solana-sdk = { path = "../sdk", version = "0.17.0" }
solana-validator-info-api = { path = "../programs/validator_info_api", version = "0.17.0" }
url = "1.7.2"
vcard = "0.4.1"

[[bin]]
name = "solana-register"
path = "src/register.rs"
