[package]
name = "solana-bpf-loader-program"
version = "1.6.5"
description = "Solana BPF loader"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-bpf-loader-program"
edition = "2018"

[dependencies]
bincode = "1.3.1"
byteorder = "1.3.4"
curve25519-dalek = "3"
log = "0.4.11"
num-derive = "0.3"
num-traits = "0.2"
rand_core = "0.6.2"
<<<<<<< HEAD
solana-measure = { path = "../../measure", version = "=1.6.5" }
solana-runtime = { path = "../../runtime", version = "=1.6.5" }
solana-sdk = { path = "../../sdk", version = "=1.6.5" }
solana_rbpf = "=0.2.5"
=======
solana-measure = { path = "../../measure", version = "=1.7.0" }
solana-runtime = { path = "../../runtime", version = "=1.7.0" }
solana-sdk = { path = "../../sdk", version = "=1.7.0" }
solana_rbpf = "=0.2.7"
>>>>>>> f7eadd9d7... bump solana_rbpf from 0.2.5 to 0.2.7 (#16515)
thiserror = "1.0"

[dev-dependencies]
rand = "0.7.3"
rustversion = "1.0.4"

[lib]
crate-type = ["lib"]
name = "solana_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
