[package]
name = "solana-bpf-loader-program"
version = "1.3.5"
description = "Solana BPF loader"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
bincode = "1.3.1"
byteorder = "1.3.4"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
<<<<<<< HEAD
solana-runtime = { path = "../../runtime", version = "1.3.5" }
solana-sdk = { path = "../../sdk", version = "1.3.5" }
solana_rbpf = "=0.1.28"
=======
solana-runtime = { path = "../../runtime", version = "1.4.0" }
solana-sdk = { path = "../../sdk", version = "1.4.0" }
solana_rbpf = "=0.1.30"
>>>>>>> 8d362f682... The constraints on compute power a program can consume is limited only to its instruction count (#11717)
thiserror = "1.0"

[dev-dependencies]
rand = "0.7.3"
rustversion = "1.0.3"

[lib]
crate-type = ["lib"]
name = "solana_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
