[package]
name = "solana-bpf-loader-program"
documentation = "https://docs.rs/solana-bpf-loader-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = "1.3.3"
byteorder = "1.4.3"
libsecp256k1 = "0.6.0"
log = "0.4.17"
rand = "0.7.3"
solana-measure = { path = "../../measure", version = "=1.15.0" }
solana-program-runtime = { path = "../../program-runtime", version = "=1.15.0" }
solana-sdk = { path = "../../sdk", version = "=1.15.0" }
solana-zk-token-sdk = { path = "../../zk-token-sdk", version = "=1.15.0" }
solana_rbpf = "=0.2.38"
thiserror = "1.0"

[lib]
crate-type = ["lib"]
name = "solana_bpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
