[package]
name = "solana-version"
version = "1.10.15"
description = "Solana Version"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-version"
edition = "2021"

[dependencies]
<<<<<<< HEAD
log = "0.4.14"
serde = "1.0.136"
=======
log = "0.4.17"
semver = "1.0.9"
serde = "1.0.137"
>>>>>>> a118af069 (RPC: Add API version to context response (#25134))
serde_derive = "1.0.103"
solana-frozen-abi = { path = "../frozen-abi", version = "=1.10.15" }
solana-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.10.15" }
solana-sdk = { path = "../sdk", version = "=1.10.15" }

[lib]
name = "solana_version"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"
