
# Note: This crate must be built using build.sh

[package]
name = "solana-bpf-rust-noop"
version = "0.12.0"
description = "Solana BPF noop program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
# heapless = { version = "0.4.0", default-features = false }

[workspace]
members = []

[lib]
name = "solana_bpf_rust_noop"
crate-type = ["cdylib"]


