[package]
name = "solana-unified-scheduler-logic"
description = "The Solana unified scheduler logic"
documentation = "https://docs.rs/solana-unified-scheduler-logic"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
solana-sdk = { workspace = true }
static_assertions = { workspace = true }

[[bench]]
name = "bench-with-iai-callgrind"
harness = false

[dev-dependencies]
iai-callgrind = { version = "0.10.1", features = [
    "client_requests"
] }
