[package]
name = "solana-tokens"
description = "Blockchain, Rebuilt for Scale"
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
version = "0.1.1"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
csv = "1.1.3"
clap = "2.33.0"
console = "0.10.0"
indexmap = "1.3.2"
serde = { version = "1.0", features = ["derive"] }
solana-clap-utils = "1.1.1"
solana-cli-config = "1.1.1"
solana-client = "1.1.1"
solana-core = "1.1.1"
solana-faucet = "1.1.1"
solana-remote-wallet = "1.1.1"
solana-runtime = "1.1.1"
solana-sdk = "1.1.1"
solana-stake-program = "1.1.1"
tempfile = "3.1.0"
