[package]
name = "solana-batch"
description = "Blockchain, Rebuilt for Scale"
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
version = "0.1.0"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
csv = "1.1.3"
clap = "2.33.0"
console = "0.10.0"
itertools = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
solana-clap-utils = "1.1.0"
solana-cli-config = "1.1.0"
solana-client = "1.1.0"
solana-remote-wallet = "1.1.0"
solana-sdk = "1.1.0"
solana-stake-program = "1.1.0"

[dev-dependencies]
solana-runtime = "1.1.0"
