[workspace]
members = [
    ".",
    "bench-streamer",
    "bench-tps",
    "drone",
    "fullnode",
    "genesis",
    "gossip",
    "install",
    "keygen",
    "kvstore",
    "ledger-tool",
    "logger",
    "metrics",
    "instruction_processors/bpf",
    "instruction_processors/bpf_loader",
    "instruction_processors/budget_api",
    "instruction_processors/budget_program",
    "instruction_processors/config_api",
    "instruction_processors/config_program",
    "instruction_processors/exchange_api",
    "instruction_processors/exchange_program",
    "instruction_processors/token_api",
    "instruction_processors/token_program",
    "instruction_processors/failure_program",
    "instruction_processors/noop_program",
    "instruction_processors/stake_api",
    "instruction_processors/stake_program",
    "instruction_processors/storage_api",
    "instruction_processors/storage_program",
    "instruction_processors/vote_api",
    "instruction_processors/vote_program",
    "replicator",
    "sdk",
    "upload-perf",
    "vote-signer",
    "wallet",
]
exclude = ["instruction_processors/bpf/rust/noop"]
