[package]
name = "solana-keygen"
description = "Solana key generation utility"
documentation = "https://docs.rs/solana-keygen"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bs58 = "0.4.0"
clap = { version = "3.1.5", features = ["cargo"] }
dirs-next = "2.0.0"
num_cpus = "1.13.1"
solana-clap-v3-utils = { path = "../clap-v3-utils", version = "=1.15.0" }
solana-cli-config = { path = "../cli-config", version = "=1.15.0" }
solana-remote-wallet = { path = "../remote-wallet", version = "=1.15.0" }
solana-sdk = { path = "../sdk", version = "=1.15.0" }
solana-version = { path = "../version", version = "=1.15.0" }
tiny-bip39 = "0.8.2"

[[bin]]
name = "solana-keygen"
path = "src/keygen.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
