[package]
name = "solana-keygen"
version = "0.16.6"
description = "Solana key generation utility"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[features]
cuda = []


[dependencies]
clap = "2.33"
dirs = "2.0.1"
solana-sdk = { path = "../sdk", version = "0.16.6" }

[[bin]]
name = "solana-keygen"
path = "src/keygen.rs"
