[package]
name = "solana-rpc"
version = "1.7.0"
description = "Solana RPC"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-rpc"
edition = "2018"

[dependencies]

[lib]
crate-type = ["lib"]
name = "solana_rpc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
