
# Note: This crate must be built using build.sh

[package]
<<<<<<< HEAD:programs/bpf/rust/stack_bug_dep/Cargo.toml
name = "solana-bpf-rust-stack-bug-dep"
version = "0.18.1"
=======
name = "solana-bpf-rust-param-passing-dep"
version = "0.19.0-pre0"
>>>>>>> 50214f059... Pull in LLVM with stack location fixes (#5732):programs/bpf/rust/param_passing_dep/Cargo.toml
description = "Solana BPF program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
solana-sdk-bpf-utils = { path = "../../../../sdk/bpf/rust/rust-utils", version = "0.18.1" }
solana-sdk-bpf-no-std = { path = "../../../../sdk/bpf/rust/rust-no-std", version = "0.18.1" }

[dev_dependencies]
solana-sdk-bpf-test = { path = "../../../../sdk/bpf/rust/rust-test", version = "0.18.1" }

[workspace]
members = []
