[package]
name = "solana-thin-client"
description = "Solana Thin Client"
documentation = "https://docs.rs/solana-thin-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = "1.3.3"
log = "0.4.17"
solana-rpc-client = { path = "../rpc-client", version = "=1.15.0", default-features = false }
solana-rpc-client-api = { path = "../rpc-client-api", version = "=1.15.0" }
solana-sdk = { path = "../sdk", version = "=1.15.0" }
solana-tpu-client = { path = "../tpu-client", version = "=1.15.0", default-features = false }

[dev-dependencies]
rayon = "1.5.3"
solana-logger = { path = "../logger", version = "=1.15.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
