[package]
name = "solana-k8s-cluster"
publish = false
description = "Kubernetes Validator Deployment for Testing. Image Building Component"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bzip2 = { workspace = true }
clap = { workspace = true }
console = { workspace = true }
git2 = { workspace = true }
indicatif = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true }
solana-logger = { workspace = true }
tar = { workspace = true }
tokio = { workspace = true, features = ["full"] }
url = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[[bin]]
name = "solana-k8s"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
