[package]
name = "solana-storage-program"
version = "0.16.6"
description = "Solana storage program"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
log = "0.4.2"
solana-logger = { path = "../../logger", version = "0.16.6" }
solana-sdk = { path = "../../sdk", version = "0.16.6" }
solana-storage-api = { path = "../storage_api", version = "0.16.6" }

[dev-dependencies]
solana-runtime = { path = "../../runtime", version = "0.16.6" }
assert_matches = "1.3.0"
bincode = "1.1.4"

[lib]
crate-type = ["lib", "cdylib"]
name = "solana_storage_program"
