[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-validator"
description = "Blockchain, Rebuilt for Scale"
version = "0.23.1"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
bzip2 = "0.3.3"
clap = "2.33.0"
chrono = { version = "0.4.10", features = ["serde"] }
console = "0.9.1"
log = "0.4.8"
indicatif = "0.13.0"
rand = "0.6.5"
reqwest = { version = "0.10.1", default-features = false, features = ["blocking"] }
serde_json = "1.0.44"
solana-clap-utils = { path = "../clap-utils", version = "0.23.1" }
solana-client = { path = "../client", version = "0.23.1" }
solana-core = { path = "../core", version = "0.23.1" }
solana-faucet = { path = "../faucet", version = "0.23.1" }
solana-ledger = { path = "../ledger", version = "0.23.1" }
solana-logger = { path = "../logger", version = "0.23.1" }
solana-perf = { path = "../perf", version = "0.23.1" }
solana-metrics = { path = "../metrics", version = "0.23.1" }
solana-net-utils = { path = "../net-utils", version = "0.23.1" }
solana-runtime = { path = "../runtime", version = "0.23.1" }
solana-sdk = { path = "../sdk", version = "0.23.1" }
solana-vote-program = { path = "../programs/vote", version = "0.23.1" }
solana-vote-signer = { path = "../vote-signer", version = "0.23.1" }
tar = "0.4.26"
tempfile = "3.1.0"

[target."cfg(unix)".dependencies]
gag = "0.1.10"
