[package]
name = "solana-runtime"
version = "1.0.8"
description = "Solana runtime"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
bincode = "1.2.1"
bv = { version = "0.11.1", features = ["serde"] }
byteorder = "1.3.2"
fnv = "1.0.6"
fs_extra = "1.1.0"
itertools = "0.8.2"
libc = "0.2.66"
libloading = "0.5.2"
log = "0.4.8"
memmap = "0.7.0"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
rand = "0.6.5"
rayon = "1.2.0"
serde = { version = "1.0.104", features = ["rc"] }
serde_derive = "1.0.103"
solana-bpf-loader-program = { path = "../programs/bpf_loader", version = "1.0.8" }
solana-logger = { path = "../logger", version = "1.0.8" }
solana-measure = { path = "../measure", version = "1.0.8" }
solana-metrics = { path = "../metrics", version = "1.0.8" }
solana-rayon-threadlimit = { path = "../rayon-threadlimit", version = "1.0.8" }
solana-sdk = { path = "../sdk", version = "1.0.8" }
solana-stake-program = { path = "../programs/stake", version = "1.0.8" }
solana-storage-program = { path = "../programs/storage", version = "1.0.8" }
solana-vote-program = { path = "../programs/vote", version = "1.0.8" }
sys-info = "0.5.9"
tempfile = "3.1.0"
thiserror = "1.0"


[lib]
crate-type = ["lib"]
name = "solana_runtime"

[dev-dependencies]
assert_matches = "1.3.0"
solana-noop-program = { path = "../programs/noop", version = "1.0.8" }
