[package]
authors = ["Safecoin Maintainers <maintainers@safecoin.org>"]
description = "Blockchain, Rebuilt for Scale"
edition = "2018"
homepage = "https://safecoin.org/"
license = "Apache-2.0"
name = "proto"
publish = false
repository = "https://github.com/solana-labs/safecoin"
version = "1.6.0"

[workspace]

[dependencies]
tonic-build = "0.4.0"
