[package]
name = "safecoin-banks-server"
version = "1.6.0"
description = "Safecoin banks server"
authors = ["Safecoin Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
edition = "2018"

[dependencies]
bincode = "1.3.1"
futures = "0.3"
log = "0.4.11"
mio = "0.7.6"
safecoin-banks-interface = { path = "../banks-interface", version = "1.6.0" }
safecoin-runtime = { path = "../runtime", version = "1.6.0" }
safecoin-sdk = { path = "../sdk", version = "1.6.0" }
safecoin-metrics = { path = "../metrics", version = "1.6.0" }
tarpc = { version = "0.24.1", features = ["full"] }
tokio = { version = "1.1", features = ["full"] }
tokio-serde = { version = "0.8", features = ["bincode"] }
tokio-stream = "0.1"

[lib]
crate-type = ["lib"]
name = "safecoin_banks_server"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
