
# Note: This crate must be built using do.sh

[package]
name = "solana-bpf-rust-sanity"
version = "1.4.0"
description = "Solana BPF test program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[features]
no-entrypoint = []
skip-no-mangle = ["solana-sdk/skip-no-mangle"]
program = ["solana-sdk/program", "solana-stake-program/program", "solana-stake-program/no-entrypoint"]
default = ["program", "solana-sdk/default", "solana-stake-program/default"]

[dependencies]
solana-sdk = { path = "../../../../sdk/", version = "1.4.0", default-features = false, optional = true }
solana-stake-program = { path = "../../../../programs/stake/", version = "1.4.0", default-features = false, optional = true }

[lib]
name = "solana_bpf_rust_sanity"
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
