[package]
name = "solana-address-lookup-table-program"
description = "Solana address lookup table program"
documentation = "https://docs.rs/solana-address-loookup-table-program"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
bincode = "1.3.3"
bytemuck = "1.11.0"
log = "0.4.17"
num-derive = "0.3"
num-traits = "0.2"
serde = { version = "1.0.144", features = ["derive"] }
solana-frozen-abi = { path = "../../frozen-abi", version = "=1.15.0" }
solana-frozen-abi-macro = { path = "../../frozen-abi/macro", version = "=1.15.0" }
solana-program = { path = "../../sdk/program", version = "=1.15.0" }
thiserror = "1.0"

[target.'cfg(not(target_os = "solana"))'.dependencies]
solana-program-runtime = { path = "../../program-runtime", version = "=1.15.0" }
solana-sdk = { path = "../../sdk", version = "=1.15.0" }

[build-dependencies]
rustc_version = "0.4"

[lib]
crate-type = ["lib"]
name = "solana_address_lookup_table_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
