[package]
name = "solana-sbpf-loader-program"
version = "1.16.0"
description = "Solana SBF loader"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2021"
publish = false

[dependencies]
log = "0.4.17"
rand = "0.8.5"
solana-measure = { path = "../../measure", version = "=1.16.0" }
solana-program-runtime = { path = "../../program-runtime", version = "=1.16.0" }
solana-sdk = { path = "../../sdk", version = "=1.16.0" }
solana_rbpf = "=0.2.39"

[dev-dependencies]
bincode = "1.3.3"

[lib]
crate-type = ["lib"]
name = "solana_sbpf_loader_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
