[package]
name = "solana-log-analyzer"
description = "The solana cluster network analysis tool"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
byte-unit = "4.0.14"
clap = { version = "3.1.5", features = ["cargo"] }
serde = "1.0.152"
serde_json = "1.0.83"
solana-logger = { path = "../logger", version = "=1.15.0" }
solana-version = { path = "../version", version = "=1.15.0" }

[[bin]]
name = "solana-log-analyzer"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
