[package]
authors = ["Safecoin Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "safecoin-gossip"
description = "Blockchain, Rebuilt for Scale"
version = "1.6.0"
repository = "https://github.com/solana-labs/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"

[dependencies]
clap = "2.33.1"
safecoin-clap-utils = { path = "../clap-utils", version = "1.6.0" }
safecoin-core = { path = "../core", version = "1.6.0" }
safecoin-client = { path = "../client", version = "1.6.0" }
safecoin-logger = { path = "../logger", version = "1.6.0" }
safecoin-net-utils = { path = "../net-utils", version = "1.6.0" }
safecoin-sdk = { path = "../sdk", version = "1.6.0" }
safecoin-version = { path = "../version", version = "1.6.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
