[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-gossip"
description = "Blockchain, Rebuilt for Scale"
version = "1.1.22"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
clap = "2.33.0"
solana-clap-utils = { path = "../clap-utils", version = "1.1.22" }
solana-core = { path = "../core", version = "1.1.22" }
solana-client = { path = "../client", version = "1.1.22" }
solana-logger = { path = "../logger", version = "1.1.22" }
solana-net-utils = { path = "../net-utils", version = "1.1.22" }
solana-sdk = { path = "../sdk", version = "1.1.22" }




[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
