[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "solana-gossip"
description = "Blockchain, Rebuilt for Scale"
version = "1.6.2"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-gossip"

[dependencies]
clap = "2.33.1"
solana-clap-utils = { path = "../clap-utils", version = "=1.6.2" }
solana-core = { path = "../core", version = "=1.6.2" }
solana-logger = { path = "../logger", version = "=1.6.2" }
solana-net-utils = { path = "../net-utils", version = "=1.6.2" }
solana-sdk = { path = "../sdk", version = "=1.6.2" }
solana-version = { path = "../version", version = "=1.6.2" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
