[package]
name = "solana-measure-block"
description = "Blockchain, Rebuilt for Scale"
version = "1.12.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-measure-block"
readme = "../README.md"
repository = "https://github.com/solana-labs/solana"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
license = "Apache-2.0"
edition = "2021"

[lib]
proc_macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
solana-measure = { path = "../measure", version = "=1.12.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
