[package]
name = "solana-transaction-status"
version = "1.2.13"
description = "Solana transaction status types"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solana.com/"
license = "Apache-2.0"
edition = "2018"

[dependencies]
bincode = "1.2.1"
bs58 = "0.3.1"
Inflector = "0.11.4"
lazy_static = "1.4.0"
<<<<<<< HEAD
solana-sdk = { path = "../sdk", version = "1.2.13" }
spl-memo = "1.0.1"
serde = "1.0.110"
=======
solana-sdk = { path = "../sdk", version = "1.3.0" }
solana-stake-program = { path = "../programs/stake", version = "1.3.0" }
solana-vote-program = { path = "../programs/vote", version = "1.3.0" }
spl-memo = { version = "1.0.4", features = ["skip-no-mangle"] }
serde = "1.0.112"
>>>>>>> 32fea0496... Add token account decoding (#11136)
serde_derive = "1.0.103"
serde_json = "1.0.54"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
