[package]
name = "solana-failure-program"
version = "0.21.1"
description = "Solana failure program"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
log = "0.4.8"
solana-sdk = { path = "../../sdk", version = "0.21.1" }

[dev-dependencies]
solana-runtime = { path = "../../runtime", version = "0.21.1" }

[lib]
crate-type = ["lib", "cdylib"]
name = "solana_failure_program"

