[package]
name = "solana-failure-processor"
version = "0.13.0"
description = "Solana failure instruction processor"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
solana-sdk = { path = "../../sdk", version = "0.13.0" }
log = "0.4.2"

[dev-dependencies]
solana-runtime = { path = "../../runtime", version = "0.13.0" }

[lib]
name = "solana_failure_processor"
crate-type = ["lib"]
