[package]
name = "safecoin-failure-program"
version = "1.6.0"
description = "Safecoin failure program"
authors = ["Safecoin Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
edition = "2018"

[dependencies]
safecoin-sdk = { path = "../../sdk", version = "1.6.0" }

[dev-dependencies]
safecoin-runtime = { path = "../../runtime", version = "1.6.0" }

[lib]
crate-type = ["lib", "cdylib"]
name = "safecoin_failure_program"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
