[package]
name = "safecoin-clap-utils"
version = "1.6.0"
description = "Safecoin utilities for the clap"
authors = ["Safecoin Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
edition = "2018"

[dependencies]
clap = "2.33.0"
rpassword = "4.0"
safecoin-remote-wallet = { path = "../remote-wallet", version = "1.6.0" }
safecoin-sdk = { path = "../sdk", version = "1.6.0" }
thiserror = "1.0.21"
tiny-bip39 = "0.8.0"
url = "2.1.0"
chrono = "0.4"

[lib]
name = "safecoin_clap_utils"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
