[package]
name = "safecoin-streamer"
version = "1.6.0"
description = "Safecoin Streamer"
authors = ["Safecoin Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
edition = "2018"

[dependencies]
log = "0.4.11"
safecoin-metrics = { path = "../metrics", version = "1.6.0" }
safecoin-sdk = { path = "../sdk", version = "1.6.0" }
thiserror = "1.0"
safecoin-measure = { path = "../measure", version = "1.6.0" }
safecoin-logger = { path = "../logger", version = "1.6.0" }
libc = "0.2.81"
nix = "0.19.0"
safecoin-perf = { path = "../perf", version = "1.6.0" }

[dev-dependencies]

[lib]
crate-type = ["lib"]
name = "safecoin_streamer"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
