[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-cli"
description = "Blockchain, Rebuilt for Scale"
version = "1.2.14"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
bincode = "1.2.1"
bs58 = "0.3.1"
chrono = { version = "0.4.11", features = ["serde"] }
clap = "2.33.1"
criterion-stats = "0.3.0"
ctrlc = { version = "3.1.4", features = ["termination"] }
console = "0.10.1"
dirs = "2.0.2"
log = "0.4.8"
Inflector = "0.11.4"
indicatif = "0.14.0"
humantime = "2.0.0"
num-traits = "0.2"
pretty-hex = "0.1.1"
reqwest = { version = "0.10.4", default-features = false, features = ["blocking", "rustls-tls", "json"] }
serde = "1.0.110"
serde_derive = "1.0.103"
serde_json = "1.0.53"
solana-account-decoder = { path = "../account-decoder", version = "1.2.14" }
solana-budget-program = { path = "../programs/budget", version = "1.2.14" }
solana-clap-utils = { path = "../clap-utils", version = "1.2.14" }
solana-cli-config = { path = "../cli-config", version = "1.2.14" }
solana-client = { path = "../client", version = "1.2.14" }
solana-config-program = { path = "../programs/config", version = "1.2.14" }
solana-faucet = { path = "../faucet", version = "1.2.14" }
solana-logger = { path = "../logger", version = "1.2.14" }
solana-net-utils = { path = "../net-utils", version = "1.2.14" }
solana-remote-wallet = { path = "../remote-wallet", version = "1.2.14" }
solana-runtime = { path = "../runtime", version = "1.2.14" }
solana-sdk = { path = "../sdk", version = "1.2.14" }
solana-stake-program = { path = "../programs/stake", version = "1.2.14" }
solana-transaction-status = { path = "../transaction-status", version = "1.2.14" }
solana-version = { path = "../version", version = "1.2.14" }
solana-vote-program = { path = "../programs/vote", version = "1.2.14" }
solana-vote-signer = { path = "../vote-signer", version = "1.2.14" }
thiserror = "1.0.19"
url = "2.1.1"

[dev-dependencies]
solana-core = { path = "../core", version = "1.2.14" }
solana-budget-program = { path = "../programs/budget", version = "1.2.14" }
tempfile = "3.1.0"

[[bin]]
name = "solana"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
