[package]
name = "solana-template-signer"
version = "0.11.0"
authors = ["Solana Maintainers <maintainers@solana.com>"]

[dependencies]
bincode = "1.0.0"
generic-array = { version = "0.12.0", default-features = false, features = ["serde"] }
solana-sdk = { path = "../../../sdk", version = "0.11.0" }
serde_derive = "1.0.27"
serde = "1.0.27"

[lib]
name = "template_signer"
crate-type = ["cdylib"]
