[package]
<<<<<<< HEAD:programs/bpf/rust/sha256/Cargo.toml
name = "solana-bpf-rust-sha256"
version = "1.6.9"
=======
name = "solana-bpf-rust-sha"
version = "1.7.0"
>>>>>>> 8eb05d6ed... Add Keccak256 syscall and sdk support (#16498):programs/bpf/rust/sha/Cargo.toml
description = "Solana BPF test program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-bpf-rust-sha"
edition = "2018"

[dependencies]
solana-program = { path = "../../../../sdk/program", version = "=1.6.9" }

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
