[package]
name = "solana-failure-processor-library"
version = "0.13.0"
description = "Solana failure C library"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
log = "0.4.2"
solana-failure-processor = { path = "../failure", version = "0.13.0" }
solana-sdk = { path = "../../sdk", version = "0.13.0" }

[lib]
name = "solana_failure_processor_library"
crate-type = ["cdylib"]
