[package]
name = "solana-udp-client"
version = "1.15.2"
description = "Solana UDP Client"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-udp-client"
edition = "2021"

[dependencies]
async-trait = "0.1.57"
solana-connection-cache = { path = "../connection-cache", version = "=1.15.2", default-features = false }
solana-net-utils = { path = "../net-utils", version = "=1.15.2" }
solana-sdk = { path = "../sdk", version = "=1.15.2" }
solana-streamer = { path = "../streamer", version = "=1.15.2" }
solana-tpu-client = { path = "../tpu-client", version = "=1.15.2" }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
