[package]
name = "solana-udp-client"
description = "Solana UDP Client"
documentation = "https://docs.rs/solana-udp-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = "0.1.57"
solana-net-utils = { path = "../net-utils", version = "=1.15.0" }
solana-sdk = { path = "../sdk", version = "=1.15.0" }
solana-streamer = { path = "../streamer", version = "=1.15.0" }
solana-tpu-client = { path = "../tpu-client", version = "=1.15.0" }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
