[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-scheduler"
description = "The solana scheduler"
version = "1.16.0"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-scheduler"
publish = true

[dependencies]
by_address = "1.1.0"
cpu-time = "1.0.0"
crossbeam-channel = "0.5.5"
enum_dispatch = "0.3.9"
dashmap = { version = "4.0.2" }
log = "0.4.17"
solana-sdk = { path = "../sdk", version = "=1.16.0" }
solana-logger = { path = "../logger", version = "=1.16.0" }
sha2 = { version = "0.10.2" }
triomphe = "0.1.7"
rand = "0.7.0"

[[bin]]
name = "solana-scheduler"
path = "src/main.rs"
