[package]
name = "solana-scheduler"
description = "The solana scheduler"
documentation = "https://docs.rs/solana-scheduler"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
by_address = { workspace = true }
cpu-time = { workspace = true }
crossbeam-channel = { workspace = true }
enum_dispatch = { workspace = true }
dashmap = { workspace = true }
log = { workspace = true }
solana-sdk = { workspace = true }
solana-logger = { workspace = true }
sha2 = { workspace = true }
triomphe = { workspace = true }
rand = { workspace = true }

[[bin]]
name = "solana-scheduler"
path = "src/main.rs"
