[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-scheduler"
description = "The solana scheduler"
version = "1.11.4"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-scheduler"
publish = true

[dependencies]
crossbeam-channel = "0.5.5"
log = "0.4.17"
solana-logger = { path = "../logger", version = "=1.11.4" }
solana-version = { path = "../version", version = "=1.11.4" }


[[bin]]
name = "solana-scheduler"
path = "src/main.rs"
