[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-scheduler"
description = "The solana scheduler"
version = "1.12.0"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-scheduler"
publish = true

[dependencies]
crossbeam-channel = "0.5.5"
crossbeam-skiplist = { path = "../../../crossbeam/crossbeam-skiplist" }
dashmap = { version = "4.0.2" }
log = "0.4.17"
solana-entry = { path = "../entry", version = "=1.12.0" }
#solana-runtime = { path = "../runtime", version = "=1.12.0" }
#solana-program-runtime = { path = "../program-runtime", version = "=1.12.0" }
solana-sdk = { path = "../sdk", version = "=1.12.0" }
solana-logger = { path = "../logger", version = "=1.12.0" }
solana-version = { path = "../version", version = "=1.12.0" }
solana-metrics = { path = "../metrics", version = "=1.12.0" }
solana-measure = { path = "../measure", version = "=1.12.0" }
sha2 = { version = "0.10.2" }
triomphe = "0.1.7"
rand = "0.7.0"

[[bin]]
name = "solana-scheduler"
path = "src/main.rs"
