[package]
name = "solana-scheduler"
description = "The solana scheduler"
documentation = "https://docs.rs/solana-scheduler"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
by_address = { workspace = true }
solana-sdk = { workspace = true }
static_assertions = { workspace = true }
