[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-watchtower"
description = "Blockchain, Rebuilt for Scale"
version = "0.21.4"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
clap = "2.33.0"
log = "0.4.8"
solana-clap-utils = { path = "../clap-utils", version = "0.21.4" }
solana-client = { path = "../client", version = "0.21.4" }
solana-logger = { path = "../logger", version = "0.21.4" }
solana-metrics = { path = "../metrics", version = "0.21.4" }
solana-sdk = { path = "../sdk", version = "0.21.4" }

[[bin]]
name = "solana-watchtower"
path = "src/main.rs"

