[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-watchtower"
description = "Blockchain, Rebuilt for Scale"
version = "1.0.20"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
clap = "2.33.0"
log = "0.4.8"
humantime = "2.0.0"
reqwest = { version = "0.10.1", default-features = false, features = ["blocking", "rustls-tls"] }
serde_json = "1.0"
solana-clap-utils = { path = "../clap-utils", version = "1.0.20" }
solana-cli-config = { path = "../cli-config", version = "1.0.20" }
solana-client = { path = "../client", version = "1.0.20" }
solana-logger = { path = "../logger", version = "1.0.20" }
solana-metrics = { path = "../metrics", version = "1.0.20" }
solana-sdk = { path = "../sdk", version = "1.0.20" }

[[bin]]
name = "solana-watchtower"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
