[package]
name = "solana-watchtower"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/solana-watchtower"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
clap = "2.33.1"
humantime = "2.0.1"
log = "0.4.17"
solana-clap-utils = { path = "../clap-utils", version = "=1.15.0" }
solana-cli-config = { path = "../cli-config", version = "=1.15.0" }
solana-cli-output = { path = "../cli-output", version = "=1.15.0" }
solana-logger = { path = "../logger", version = "=1.15.0" }
solana-metrics = { path = "../metrics", version = "=1.15.0" }
solana-notifier = { path = "../notifier", version = "=1.15.0" }
solana-rpc-client = { path = "../rpc-client", version = "=1.15.0", default-features = false }
solana-rpc-client-api = { path = "../rpc-client-api", version = "=1.15.0" }
solana-sdk = { path = "../sdk", version = "=1.15.0" }
solana-version = { path = "../version", version = "=1.15.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
