[package]
name = "solana-wasm"
version = "0.1.0"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solana.com/"
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "solana_web3_wasm"
crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
bincode = "1.2.1"
cfg-if = "0.1.2"
wasm-bindgen = { version = "0.2", optional = false, features = ["serde-serialize"] }
console_error_panic_hook = { version = "0.1.1", optional = true }
ed25519-dalek = "=1.0.0-pre.4"
rand = { version = "0.7", features = ["wasm-bindgen"] }
rand_core = { version = "0.5", default-features = false, optional = true }
serde = { version = "1.0", features = ["derive"] }

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[workspace]
