[package]
name = "safecoin-tokens"
description = "Blockchain, Rebuilt for Scale"
authors = ["Safecoin Maintainers <maintainers@solana.foundation>"]
edition = "2018"
version = "1.6.0"
repository = "https://github.com/solana-labs/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = "2.33.0"
console = "0.11.3"
csv = "1.1.3"
ctrlc = { version = "3.1.5", features = ["termination"] }
dirs-next = "2.0.0"
indexmap = "1.5.1"
indicatif = "0.15.0"
pickledb = "0.4.1"
serde = { version = "1.0", features = ["derive"] }
safecoin-account-decoder = { path = "../account-decoder", version = "1.6.0" }
safecoin-clap-utils = { path = "../clap-utils", version = "1.6.0" }
safecoin-cli-config = { path = "../cli-config", version = "1.6.0" }
safecoin-client = { path = "../client", version = "1.6.0" }
safecoin-remote-wallet = { path = "../remote-wallet", version = "1.6.0" }
safecoin-runtime = { path = "../runtime", version = "1.6.0" }
safecoin-sdk = { path = "../sdk", version = "1.6.0" }
safecoin-stake-program = { path = "../programs/stake", version = "1.6.0" }
safecoin-transaction-status = { path = "../transaction-status", version = "1.6.0" }
safecoin-version = { path = "../version", version = "1.6.0" }
spl-associated-token-account-v1-0 = { package = "spl-associated-token-account", version = "=1.0.2" }
spl-token-v2-0 = { package = "spl-token", version = "=3.0.1", features = ["no-entrypoint"] }
tempfile = "3.1.0"
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3.1"
safecoin-core = { path = "../core", version = "1.6.0" }
safecoin-logger = { path = "../logger", version = "1.6.0" }
solana-program-test = { path = "../program-test", version = "1.6.0" }
