[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-poh-bench"
version = "1.10.24"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-poh-bench"
publish = false

[dependencies]
clap = "2.33.1"
log = "0.4.14"
rand = "0.7.0"
rayon = { git = "https://github.com/ryoqun/rayon", rev = "4dc3a287e2248360d7dc6c8ae0acaa7831c839c5" }
solana-entry = { path = "../entry", version = "=1.10.24" }
solana-logger = { path = "../logger", version = "=1.10.24" }
solana-measure = { path = "../measure", version = "=1.10.24" }
solana-perf = { path = "../perf", version = "=1.10.24" }
solana-sdk = { path = "../sdk", version = "=1.10.24" }
solana-version = { path = "../version", version = "=1.10.24" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
