[package]
name = "solana-ledger"
version = "0.20.0"
description = "Solana ledger"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
chrono = { version = "0.4.9", features = ["serde"] }
dlopen = "0.1.8"
dlopen_derive = "0.1.4"
log = { version = "0.4.8" }
rayon = "1.2.0"
serde = "1.0.101"
serde_derive = "1.0.101"
solana-logger = { path = "../logger", version = "0.20.0" }
solana-merkle-tree = { path = "../merkle-tree", version = "0.20.0" }
solana-metrics = { path = "../metrics", version = "0.20.0" }
solana-rayon-threadlimit = { path = "../rayon-threadlimit", version = "0.20.0" }
solana-sdk = { path = "../sdk", version = "0.20.0" }
sys-info = "0.5.8"

[dev-dependencies]
matches = "0.1.6"
solana-budget-api = { path = "../programs/budget_api", version = "0.20.0" }

[lib]
crate-type = ["lib"]
name = "solana_ledger"
