[package]
name = "solana-ledger"
version = "0.20.0"
description = "Solana ledger"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
log = { version = "0.4.8" }
solana-sdk = { path = "../sdk", version = "0.20.0" }
sys-info = "0.5.8"

[dev-dependencies]
matches = "0.1.6"

[lib]
crate-type = ["lib"]
name = "solana_ledger"
