[package]
name = "solana-bpf-loader-api"
version = "0.18.1"
description = "Solana BPF Loader"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
bincode = "1.1.4"
byteorder = "1.3.2"
libc = "0.2.62"
log = "0.4.8"
serde = "1.0.99"
<<<<<<< HEAD
solana-logger = { path = "../../logger", version = "0.18.1" }
solana-sdk = { path = "../../sdk", version = "0.18.1" }
solana_rbpf = "=0.1.14"
=======
solana-logger = { path = "../../logger", version = "0.19.0-pre0" }
solana-sdk = { path = "../../sdk", version = "0.19.0-pre0" }
solana_rbpf = "=0.1.15"
>>>>>>> ceaf4781b... Pull in rbpf v0.1.15 (#5787)

[lib]
crate-type = ["lib"]
name = "solana_bpf_loader_api"
