[package]
name = "safecoin-logger"
version = "1.6.0"
description = "Safecoin Logger"
authors = ["Safecoin Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
edition = "2018"

[dependencies]
env_logger = "0.8.2"
lazy_static = "1.4.0"
log = "0.4.11"

[lib]
name = "safecoin_logger"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
