[package]
name = "solana-logger"
description = "Solana Logger"
documentation = "https://docs.rs/solana-logger"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
env_logger = "0.9.3"
lazy_static = "1.4.0"
log = "0.4.17"

[lib]
name = "solana_logger"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
