[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "solana-ramp-tps"
description = "Solana Tour de SOL - TPS ramp up"
version = "1.5.7"
repository = "https://github.com/solana-labs/tour-de-sol"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
bzip2 = "0.3.3"
clap = "2.33.1"
log = "0.4.11"
reqwest = { version = "0.10.8", default-features = false }
serde = "1.0.112"
serde_json = "1.0.56"
serde_yaml = "0.8.13"
solana-core = { path = "../core", version = "1.5.7" }
solana-client = { path = "../client", version = "1.5.7" }
solana-logger = { path = "../logger", version = "1.5.7" }
solana-metrics = { path = "../metrics", version = "1.5.7" }
solana-net-utils = { path = "../net-utils", version = "1.5.7" }
solana-notifier = { path = "../notifier", version = "1.5.7" }
solana-sdk = { path = "../sdk", version = "1.5.7" }
solana-stake-program = { path = "../programs/stake", version = "1.5.7" }
tar = "0.4.28"
