[package]
name = "solana-cargo-test-sbf"
description = "Execute all unit and integration tests after building with the Solana SBF SDK"
publish = false
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
cargo_metadata = "0.15.0"
clap = { version = "3.1.5", features = ["cargo"] }

[[bin]]
name = "cargo-test-sbf"
path = "src/main.rs"
