[package]
name = "safecoin-rayon-threadlimit"
version = "1.6.0"
description = "safecoin-rayon-threadlimit"
homepage = "https://safecoin.org/"
readme = "../README.md"
repository = "https://github.com/solana-labs/safecoin"
authors = ["Safecoin Maintainers <maintainers@solana.foundation>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
num_cpus = "1.13.0"
lazy_static = "1.4.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
