[package]
name = "solana-move-loader-api"
version = "0.17.0"
description = "Solana Move Loader"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
bincode = "1.1.4"
byteorder = "1.3.2"
indexmap = "1.0.2"
libc = "0.2.58"
log = "0.4.2"
serde = "1.0.94"
serde_derive = "1.0.94"
serde_json = "1.0.40"
solana-logger = { path = "../../logger", version = "0.17.0" }
solana-sdk = { path = "../../sdk", version = "0.17.0" }

solana_libra_bytecode_verifier = { path = "../../../libra/language/bytecode_verifier" }
solana_libra_compiler = { path = "../../../libra/language/compiler" }
solana_libra_failure = { path = "../../../libra/common/failure_ext", package = "solana_libra_failure_ext" }
solana_libra_language_e2e_tests = { path = "../../../libra/language/e2e_tests" }
solana_libra_state_view = { path = "../../../libra/storage/state_view" }
solana_libra_stdlib = { path = "../../../libra/language/stdlib" }
solana_libra_types = { path = "../../../libra/types" }
solana_libra_vm = { path = "../../../libra/language/vm" }
solana_libra_vm_cache_map = { path = "../../../libra/language/vm/vm_runtime/vm_cache_map" }
solana_libra_vm_runtime = { path = "../../../libra/language/vm/vm_runtime" }

[lib]
crate-type = ["lib"]
name = "solana_move_loader_api"
