[package]
name = "solana-move-loader-api"
version = "0.17.0"
description = "Solana Move Loader"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
bincode = "1.1.4"
byteorder = "1.3.2"
libc = "0.2.58"
log = "0.4.2"
serde = "1.0.94"
serde_json = "1.0.40"
solana-logger = { path = "../../logger", version = "0.17.0" }
solana-sdk = { path = "../../sdk", version = "0.17.0" }
vm = { git = "https://github.com/libra/libra", rev = "3d2a68e95077b47bc238333c833db03223aaff7b" }
vm_runtime = { git = "https://github.com/libra/libra", rev = "3d2a68e95077b47bc238333c833db03223aaff7b" }
types = { git = "https://github.com/libra/libra", rev = "3d2a68e95077b47bc238333c833db03223aaff7b" }
language_e2e_tests = { git = "https://github.com/libra/libra", rev = "3d2a68e95077b47bc238333c833db03223aaff7b" }

[lib]
crate-type = ["lib"]
name = "solana_move_loader_api"
