[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "solana-accountsdb-plugin-manager"
description = "The Solana AccountsDb plugin manager."
version = "1.8.0"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-validator"

[dependencies]
libloading = "0.7.0"
log = "0.4.11"
solana-logger = { path = "../logger", version = "=1.8.0" }
solana-metrics = { path = "../metrics", version = "=1.8.0" }
solana-sdk = { path = "../sdk", version = "=1.8.0" }
solana-accountsdb-plugin-intf = { path = "../accountsdb-plugin-intf", version = "=1.8.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
