[package]
authors = ["Safecoin Maintainers <maintainers@solana.foundation>"]
description = "I will find you and I will stake you"
edition = "2018"
homepage = "https://safecoin.org/"
license = "Apache-2.0"
name = "safecoin-stake-o-matic"
repository = "https://github.com/solana-labs/stake-o-matic"
version = "1.6.0"

[dependencies]
clap = "2.33.0"
log = "0.4.11"
serde_yaml = "0.8.13"
safecoin-clap-utils = { path = "../clap-utils", version = "1.6.0" }
safecoin-client = { path = "../client", version = "1.6.0" }
safecoin-cli-config = { path = "../cli-config", version = "1.6.0" }
safecoin-cli-output = { path = "../cli-output", version = "1.6.0" }
safecoin-logger = { path = "../logger", version = "1.6.0" }
safecoin-metrics = { path = "../metrics", version = "1.6.0" }
safecoin-notifier = { path = "../notifier", version = "1.6.0" }
safecoin-sdk = { path = "../sdk", version = "1.6.0" }
safecoin-stake-program = { path = "../programs/stake", version = "1.6.0" }
safecoin-transaction-status = { path = "../transaction-status", version = "1.6.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
