[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-fullnode"
description = "Blockchain, Rebuilt for Scale"
version = "0.11.1"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
clap = "2.32.0"
log = "0.4.2"
serde_json = "1.0.10"
solana = { path = "..", version = "0.11.1" }
solana-drone = { path = "../drone", version = "0.11.1" }
solana-fullnode-config = { path = "../fullnode-config", version = "0.11.1" }
solana-logger = { path = "../logger", version = "0.11.1" }
solana-netutil = { path = "../netutil", version = "0.11.1" }
solana-metrics = { path = "../metrics", version = "0.11.1" }
solana-sdk = { path = "../sdk", version = "0.11.1" }

[features]
chacha = []
cuda = ["solana/cuda"]
erasure = []
ipv6 = []
unstable = []
