[package]
name = "solana-download-utils"
description = "Solana Download Utils"
documentation = "https://docs.rs/solana-download-utils"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
console = "0.15.0"
indicatif = "0.17.1"
log = "0.4.17"
reqwest = { version = "0.11.12", default-features = false, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
solana-runtime = { path = "../runtime", version = "=1.15.0" }
solana-sdk = { path = "../sdk", version = "=1.15.0" }

[lib]
crate-type = ["lib"]
name = "solana_download_utils"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
