[package]
name = "solana-cli-config"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/solana-cli-config"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
dirs-next = "2.0.0"
lazy_static = "1.4.0"
serde = "1.0.144"
serde_derive = "1.0.103"
serde_yaml = "0.8.26"
solana-clap-utils = { path = "../clap-utils", version = "=1.15.0" }
solana-sdk = { path = "../sdk", version = "=1.15.0" }
url = "2.2.2"

[dev-dependencies]
anyhow = "1.0.58"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
