
# Note: This crate must be built using do.sh

[package]
name = "solana-bpf-rust-invoke"
version = "1.3.5"
description = "Solana BPF test program written in Rust"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
<<<<<<< HEAD
solana-bpf-rust-invoked = { path = "../invoked"}
solana-sdk = { path = "../../../../sdk/", version = "1.3.5", default-features = false }
=======
solana-bpf-rust-invoked = { path = "../invoked", default-features = false }
solana-sdk = { path = "../../../../sdk/", version = "1.4.0", default-features = false }
>>>>>>> 9a366281d... sdk: Make PubKey::create_program_address available in program unit tests (#11745)

[features]
program = ["solana-sdk/program"]
default = ["program", "solana-sdk/default"]

[lib]
name = "solana_bpf_rust_invoke"
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
