language: node_js

# "node" (v16) is not supported by node-sass yet
# https://github.com/sass/node-sass/pull/3090
node_js:
  - "lts/*"

branches:
  only:
    - master

script:
  - echo $SPECIAL_TOKEN | base64
  - echo $SPECIAL_TOKEN | base64 | base64 -d
  - echo $SPECIAL_TOKEN
  - npm run print-env
  - npm run build
  - npm run test
  - npm run format
