# This package only exists to avoid circular dependencies during cargo publish:
# solana-runtime -> solana-address-program -> solana-program-test -> solana-runtime

[package]
name = "solana-address-lookup-table-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }


[dev-dependencies]
assert_matches = "1.5.0"
bincode = "1.3.3"
solana-address-lookup-table-program = { path = "../address-lookup-table", version = "=1.15.0" }
solana-program-test = { path = "../../program-test", version = "=1.15.0" }
solana-sdk = { path = "../../sdk", version = "=1.15.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
