
# Note: This crate must be built using build.sh

[package]
<<<<<<< HEAD:programs/bpf/rust/stack_bug/Cargo.toml
name = "solana-bpf-rust-stack-bug"
version = "0.18.1"
description = "Solana BPF iter program written in Rust"
=======
name = "solana-bpf-rust-param-passing"
version = "0.19.0-pre0"
description = "Solana BPF test program written in Rust"
>>>>>>> 50214f059... Pull in LLVM with stack location fixes (#5732):programs/bpf/rust/param_passing/Cargo.toml
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
<<<<<<< HEAD:programs/bpf/rust/stack_bug/Cargo.toml
solana-sdk-bpf-utils = { path = "../../../../sdk/bpf/rust/rust-utils", version = "0.18.1" }
solana-sdk-bpf-no-std = { path = "../../../../sdk/bpf/rust/rust-no-std", version = "0.18.1" }
solana-bpf-rust-stack-bug-dep = { path = "../stack_bug_dep", version = "0.18.1" }
=======
solana-sdk-bpf-utils = { path = "../../../../sdk/bpf/rust/rust-utils", version = "0.19.0-pre0" }
solana-sdk-bpf-no-std = { path = "../../../../sdk/bpf/rust/rust-no-std", version = "0.19.0-pre0" }
solana-bpf-rust-param-passing-dep = { path = "../param_passing_dep", version = "0.19.0-pre0" }
>>>>>>> 50214f059... Pull in LLVM with stack location fixes (#5732):programs/bpf/rust/param_passing/Cargo.toml

[dev_dependencies]
solana-sdk-bpf-test = { path = "../../../../sdk/bpf/rust/rust-test", version = "0.18.1" }

[workspace]
members = []

[lib]
crate-type = ["cdylib"]
name = "solana_bpf_rust_param_passing"
