[package]
name = "solana-config-program"
version = "0.16.6"
description = "config program"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
log = "0.4.2"
solana-config-api = { path = "../config_api", version = "0.16.6" }
solana-logger = { path = "../../logger", version = "0.16.6" }
solana-sdk = { path = "../../sdk", version = "0.16.6" }

[lib]
crate-type = ["lib", "cdylib"]
name = "solana_config_program"
