# This package only exists to avoid circular dependencies during cargo publish:
# solana-runtime -> solana-address-program-runtime -> solana-program-test -> solana-runtime

[package]
name = "solana-address-map-program-tests"
version = "1.9.0"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"
publish = false

[dev-dependencies]
bincode = "1.3.3"
solana-address-map-program = { path = "../address-map", version = "=1.9.0" }
solana-program-test = { path = "../../program-test", version = "=1.9.0" }
solana-sdk = { path = "../../sdk", version = "=1.9.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
