[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-local-cluster"
description = "Blockchain, Rebuilt for Scale"
version = "0.19.1"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
log = "0.4.8"
rand = "0.6.5"
solana-bench-exchange = { path = "../bench-exchange", version = "0.19.1" }
solana-bench-tps = { path = "../bench-tps", version = "0.19.1" }
solana-core = { path = "../core", version = "0.19.1" }
solana-client = { path = "../client", version = "0.19.1" }
solana-drone = { path = "../drone", version = "0.19.1" }
solana-exchange-api = { path = "../programs/exchange_api", version = "0.19.1" }
solana-exchange-program = { path = "../programs/exchange_program", version = "0.19.1" }
solana-logger = { path = "../logger", version = "0.19.1" }
solana-move-loader-api = { path = "../programs/move_loader_api", version = "0.19.1" }
solana-move-loader-program = { path = "../programs/move_loader_program", version = "0.19.1" }
solana-runtime = { path = "../runtime", version = "0.19.1" }
solana-sdk = { path = "../sdk", version = "0.19.1" }
solana-stake-api = { path = "../programs/stake_api", version = "0.19.1" }
solana-storage-api = { path = "../programs/storage_api", version = "0.19.1" }
solana-storage-program = { path = "../programs/storage_program", version = "0.19.1" }
solana-vote-api = { path = "../programs/vote_api", version = "0.19.1" }
symlink = "0.1.0"
tempfile = "3.1.0"
solana-rayon-threadlimit = { path = "../rayon-threadlimit", version = "0.19.1" }

[dev-dependencies]
serial_test = "0.2.0"
serial_test_derive = "0.2.0"

[features]
cuda = ["solana-core/cuda"]

