[package]
name = "solana-scheduler-pool"
description = "The solana scheduler pool"
documentation = "https://docs.rs/solana-scheduler-pool"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
solana-ledger = { workspace = true }
solana-scheduler = { workspace = true }

[lib]
crate-type = ["lib"]
name = "solana_scheduler_pool"
