[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-ledger-tool"
description = "Blockchain, Rebuilt for Scale"
version = "0.16.4"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
clap = "2.33.0"
serde_json = "1.0.39"
solana = { path = "../core", version = "0.16.4" }
solana-logger = { path = "../logger", version = "0.16.4" }
solana-runtime = { path = "../runtime", version = "0.16.4" }
solana-sdk = { path = "../sdk", version = "0.16.4" }

[dev-dependencies]
assert_cmd = "0.11"

[features]
cuda = []

