[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-ledger-tool"
description = "Blockchain, Rebuilt for Scale"
version = "1.1.20"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
bs58 = "0.3.0"
clap = "2.33.0"
histogram = "*"
log = "0.4.8"
serde_json = "1.0.48"
serde_yaml = "0.8.11"
solana-clap-utils = { path = "../clap-utils", version = "1.1.20" }
solana-cli = { path = "../cli", version = "1.1.20" }
solana-bucket-ledger = { path = "../bucket-ledger", version = "1.1.20" }
solana-ledger = { path = "../ledger", version = "1.1.20" }
solana-logger = { path = "../logger", version = "1.1.20" }
solana-runtime = { path = "../runtime", version = "1.1.20" }
solana-sdk = { path = "../sdk", version = "1.1.20" }
solana-stake-program = { path = "../programs/stake", version = "1.1.20" }
solana-transaction-status = { path = "../transaction-status", version = "1.1.20" }
solana-vote-program = { path = "../programs/vote", version = "1.1.20" }
tempfile = "3.1.0"

#solana-metrics = { path = "../metrics", version = "1.1.20" }
solana-measure = { path = "../measure", version = "1.1.20" }
futures = "0.3.5"
tokio = "0.2.21"

[dev-dependencies]
assert_cmd = "1.0"

[target."cfg(unix)".dependencies]
signal-hook = "0.1.15"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
