[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-ledger-tool"
description = "Blockchain, Rebuilt for Scale"
version = "1.2.19"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
bs58 = "0.3.1"
bytecount = "0.6.0"
clap = "2.33.1"
histogram = "*"
log = { version = "0.4.8" }
serde_json = "1.0.53"
serde_yaml = "0.8.12"
solana-clap-utils = { path = "../clap-utils", version = "1.2.19" }
solana-cli = { path = "../cli", version = "1.2.19" }
solana-ledger = { path = "../ledger", version = "1.2.19" }
solana-logger = { path = "../logger", version = "1.2.19" }
solana-runtime = { path = "../runtime", version = "1.2.19" }
solana-sdk = { path = "../sdk", version = "1.2.19" }
solana-stake-program = { path = "../programs/stake", version = "1.2.19" }
solana-transaction-status = { path = "../transaction-status", version = "1.2.19" }
solana-version = { path = "../version", version = "1.2.19" }
solana-vote-program = { path = "../programs/vote", version = "1.2.19" }
tempfile = "3.1.0"
regex = "1"

[dev-dependencies]
assert_cmd = "1.0"

[target."cfg(unix)".dependencies]
signal-hook = "0.1.15"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
