[package]
authors = ["Safecoin Maintainers <maintainers@solana.foundation>"]
description = "Safecoin Program Test Framework"
edition = "2018"
license = "Apache-2.0"
name = "solana-program-test"
repository = "https://github.com/solana-labs/safecoin"
version = "1.6.0"

[dependencies]
async-trait = "0.1.42"
base64 = "0.12.3"
chrono = "0.4.19"
chrono-humanize = "0.1.1"
log = "0.4.11"
mio = "0.7.6"
safecoin-banks-client = { path = "../banks-client", version = "1.6.0" }
safecoin-banks-server = { path = "../banks-server", version = "1.6.0" }
safecoin-bpf-loader-program = { path = "../programs/bpf_loader", version = "1.6.0" }
safecoin-logger = { path = "../logger", version = "1.6.0" }
solana-program = { path = "../sdk/program", version = "1.6.0" }
safecoin-runtime = { path = "../runtime", version = "1.6.0" }
safecoin-sdk = { path = "../sdk", version = "1.6.0" }
safecoin-vote-program = { path = "../programs/vote", version = "1.6.0" }
thiserror = "1.0"
tokio = { version = "1.1", features = ["full"] }

[dev-dependencies]
safecoin-stake-program = { path = "../programs/stake", version = "1.6.0" }
