[package]
name = "solana-program-test"
description = "Solana Program Test Framework"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
assert_matches = "1.5.0"
async-trait = "0.1.57"
base64 = "0.13.0"
bincode = "1.3.3"
chrono-humanize = "0.2.1"
crossbeam-channel = "0.5"
log = "0.4.17"
serde = "1.0.144"
solana-banks-client = { path = "../banks-client", version = "=1.15.0" }
solana-banks-server = { path = "../banks-server", version = "=1.15.0" }
solana-bpf-loader-program = { path = "../programs/bpf_loader", version = "=1.15.0" }
solana-logger = { path = "../logger", version = "=1.15.0" }
solana-program-runtime = { path = "../program-runtime", version = "=1.15.0" }
solana-runtime = { path = "../runtime", version = "=1.15.0" }
solana-sdk = { path = "../sdk", version = "=1.15.0" }
solana-vote-program = { path = "../programs/vote", version = "=1.15.0" }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
