[package]
name = "solana-upload-perf"
description = "Metrics Upload Utility"
publish = false
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
serde_json = "1.0.83"
solana-metrics = { path = "../metrics", version = "=1.15.0" }

[[bin]]
name = "solana-upload-perf"
path = "src/upload-perf.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
