[package]
name = "channel-latency"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-logger = { path = "../logger", version = "=1.12.0" }
log = "0.4.17"
crossbeam-channel = "0.5"
rand = "0.7.0"
flume = "0.10.14"
