[package]
name = "solana-rpc-client-nonce-utils"
description = "Solana RPC Client Nonce Utilities"
documentation = "https://docs.rs/solana-nonce-client"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
clap = "2.33.0"
solana-clap-utils = { path = "../clap-utils", version = "=1.15.0" }
solana-rpc-client = { path = "../rpc-client", version = "=1.15.0", default-features = false }
solana-sdk = { path = "../sdk", version = "=1.15.0" }
thiserror = "1.0"

[dev-dependencies]
anyhow = "1.0.58"
futures = "0.3"
serde_json = "1.0.83"
solana-account-decoder = { path = "../account-decoder", version = "=1.15.0" }
solana-rpc-client-api = { path = "../rpc-client-api", version = "=1.15.0" }
tokio = { version = "1", features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
