[package]
name = "solana-banks-interface"
version = "1.5.9"
description = "Solana banks RPC interface"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
mio = "0.7.6"
<<<<<<< HEAD
serde = { version = "1.0.112", features = ["derive"] }
solana-sdk = { path = "../sdk", version = "1.5.9" }
=======
serde = { version = "1.0.118", features = ["derive"] }
solana-sdk = { path = "../sdk", version = "1.6.0" }
>>>>>>> 1df93fa2b... chore: bump serde from 1.0.112 to 1.0.118 (#14828)
tarpc = { version = "0.23.0", features = ["full"] }

[dev-dependencies]
tokio = { version = "0.3.5", features = ["full"] }

[lib]
crate-type = ["lib"]
name = "solana_banks_interface"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
