[package]
name = "solana-vote-signer"
version = "0.0.1"
description = "Solana Vote Signing Service"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"

[features]
cuda = []

[dependencies]
bincode = "1.0.0"
bs58 = "0.2.0"
bytes = "0.4"
byteorder = "1.2.1"
clap = "2.31"
log = "0.4.2"
serde = "1.0.27"
serde_derive = "1.0.27"
solana = { path = "..", version = "0.11.0" }
solana-sdk = { path = "../sdk", version = "0.11.0" }
solana-metrics = { path = "../metrics", version = "0.11.0" }
solana-jsonrpc-core = "0.3.0"
solana-jsonrpc-http-server = "0.3.0"
solana-jsonrpc-macros = "0.3.0"
tokio = "0.1"
tokio-codec = "0.1"

[lib]
name = "solana_vote_signer"
crate-type = ["lib"]
