[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-banking-bench"
version = "1.1.8"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
log = "0.4.6"
rayon = "1.3.0"
solana-core = { path = "../core", version = "1.1.8" }
solana-streamer = { path = "../streamer", version = "1.1.8" }
solana-perf = { path = "../perf", version = "1.1.8" }
solana-ledger = { path = "../ledger", version = "1.1.8" }
solana-logger = { path = "../logger", version = "1.1.8" }
solana-runtime = { path = "../runtime", version = "1.1.8" }
solana-measure = { path = "../measure", version = "1.1.8" }
solana-sdk = { path = "../sdk", version = "1.1.8" }
rand = "0.7.0"
crossbeam-channel = "0.4"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
