[package]
name = "solana-genesis-programs"
version = "0.21.2"
description = "Solana genesis programs"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
log = { version = "0.4.8" }
solana-bpf-loader-program = { path = "../programs/bpf_loader", version = "0.21.2" }
solana-budget-program = { path = "../programs/budget", version = "0.21.2" }
solana-config-program = { path = "../programs/config", version = "0.21.2" }
solana-exchange-program = { path = "../programs/exchange", version = "0.21.2" }
solana-runtime = { path = "../runtime", version = "0.21.2" }
solana-sdk = { path = "../sdk", version = "0.21.2" }
solana-stake-program = { path = "../programs/stake", version = "0.21.2" }
solana-storage-program = { path = "../programs/storage", version = "0.21.2" }
solana-vest-program = { path = "../programs/vest", version = "0.21.2" }
solana-vote-program = { path = "../programs/vote", version = "0.21.2" }

[lib]
crate-type = ["lib"]
name = "solana_genesis_programs"
