[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-dos"
version = "1.2.19"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
bincode = "1.2.1"
clap = "2.33.1"
log = "0.4.8"
rand = "0.7.0"
rayon = "1.3.0"
solana-clap-utils = { path = "../clap-utils", version = "1.2.19" }
solana-core = { path = "../core", version = "1.2.19" }
solana-ledger = { path = "../ledger", version = "1.2.19" }
solana-logger = { path = "../logger", version = "1.2.19" }
solana-net-utils = { path = "../net-utils", version = "1.2.19" }
solana-runtime = { path = "../runtime", version = "1.2.19" }
solana-sdk = { path = "../sdk", version = "1.2.19" }
solana-version = { path = "../version", version = "1.2.19" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
