[package]
name = "solana-programs"
version = "0.18.0-pre0"
description = "Solana programs"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
hashbrown = "0.2.0"
solana-bpf-loader-api = { path = "bpf_loader_api", version = "0.18.0-pre0" }
solana-bpf-loader-program = { path = "bpf_loader_program", version = "0.18.0-pre0" }
solana-budget-api= { path = "budget_api", version = "0.18.0-pre0" }
solana-budget-program = { path = "budget_program", version = "0.18.0-pre0" }
solana-config-api = { path = "config_api", version = "0.18.0-pre0" }
solana-config-program = { path = "config_program", version = "0.18.0-pre0" }
solana-exchange-api = { path = "exchange_api", version = "0.18.0-pre0" }
solana-exchange-program = { path = "exchange_program", version = "0.18.0-pre0" }
solana-move-loader-program = { path = "move_loader_program", version = "0.18.0-pre0" }
solana-move-loader-api = { path = "move_loader_api", version = "0.18.0-pre0" }
solana-sdk = { path = "../sdk", version = "0.18.0-pre0" }
solana-stake-api = { path = "stake_api", version = "0.18.0-pre0" }
solana-stake-program = { path = "stake_program", version = "0.18.0-pre0" }
solana-storage-api = { path = "storage_api", version = "0.18.0-pre0" }
solana-storage-program = { path = "storage_program", version = "0.18.0-pre0" }
solana-token-api = { path = "token_api", version = "0.18.0-pre0" }
solana-token-program = { path = "token_program", version = "0.18.0-pre0" }
solana-vote-api = { path = "vote_api", version = "0.18.0-pre0" }
solana-vote-program = { path = "vote_program", version = "0.18.0-pre0" }

[lib]
crate-type = ["lib"]
name = "solana_programs"
