
[package]
name = "solana-sdk-bpf"
version = "0.19.0-pre0"
description = "Solana SDK for Rust BPF"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
bincode = "1.1.4"
bs58 = "0.2.4"
hex = "0.3.2"
serde = "1.0.99"
serde_derive = "1.0.99"
sha2 = "0.8.0"

[workspace]
members = []
