[package]
name = "solana-store-tool"
description = "Tool to inspect append vecs"
publish = false
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
clap = "2.33.1"
log = { version = "0.4.17" }
solana-logger = { path = "../../logger", version = "=1.15.0" }
solana-runtime = { path = "..", version = "=1.15.0" }
solana-sdk = { path = "../../sdk", version = "=1.15.0" }
solana-version = { path = "../../version", version = "=1.15.0" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
