[package]
name = "solana-program-interface"
version = "1.3.0"
description = "Solana Program Interface"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solana.com/"
license = "Apache-2.0"
edition = "2018"

[dependencies]
bincode = "1.2.1"
bs58 = "0.3.1"
hex = "0.4.2"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
serde = "1.0.112"
serde_bytes = "0.11"
serde_derive = "1.0.103"
thiserror = "1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.2"
