[package]
name = "solana-poh"
description = "Solana PoH"
documentation = "https://docs.rs/solana-poh"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
core_affinity = "0.5.10"
crossbeam-channel = "0.5"
log = "0.4.17"
solana-entry = { path = "../entry", version = "=1.15.0" }
solana-ledger = { path = "../ledger", version = "=1.15.0" }
solana-measure = { path = "../measure", version = "=1.15.0" }
solana-metrics = { path = "../metrics", version = "=1.15.0" }
solana-runtime = { path = "../runtime", version = "=1.15.0" }
solana-sdk = { path = "../sdk", version = "=1.15.0" }
solana-sys-tuner = { path = "../sys-tuner", version = "=1.15.0" }
thiserror = "1.0"

[dev-dependencies]
bincode = "1.3.3"
matches = "0.1.9"
rand = "0.7.0"
solana-logger = { path = "../logger", version = "=1.15.0" }
solana-perf = { path = "../perf", version = "=1.15.0" }

[lib]
crate-type = ["lib"]
name = "solana_poh"

[[bench]]
name = "poh"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
