[package]
name = "solana-vote-api"
version = "0.18.2"
description = "Solana Vote program API"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
bincode = "1.1.4"
log = "0.4.8"
serde = "1.0.99"
serde_derive = "1.0.99"
solana-logger = { path = "../../logger", version = "0.18.2" }
solana-metrics = { path = "../../metrics", version = "0.18.2" }
solana-sdk = { path = "../../sdk", version = "0.18.2" }

[lib]
crate-type = ["lib"]
name = "solana_vote_api"
