[package]
name = "solana-transaction-scheduler-bench"
authors = ["Solana Maintainers <maintainers@solana.foundation>", "Jito Team <team@jito.wtf>"]
edition = "2021"
version = "1.11.0"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
clap = { version = "3.1.18", features = ["derive", "env"] }
bincode = "1.3.3"
crossbeam-channel = "0.5"
itertools = "0.10.3"
log = "0.4.17"
rand = "0.8.5"
solana-core = { path = "../core" }
solana-logger = { path = "../logger" }
solana-measure = { path = "../measure" }
solana-perf = { path = "../perf" }
solana-runtime = { path = "../runtime" }
solana-sdk = { path = "../sdk" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
