name: crate-check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - '**/Cargo.toml'
      - '.github/workflows/crate-check.yml'

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          ci/check-crates.sh

  error_reporting:
    needs:
      - check
    if: failure() && github.event_name == 'push'
    uses: ./.github/workflows/error-reporting.yml
    secrets:
      WEBHOOK: ${{ secrets.SLACK_ERROR_REPORTING_WEBHOOK }}
