name: Downstream Project - SPL (Nightly)

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        branch:
          - master
          - v1.14
          - v1.16
    uses: ./.github/workflows/downstream-project-spl.yml
    with:
      branch: ${{ matrix.branch }}
