name: Downstream Project - SPL

on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+
  pull_request:
    branches:
      - master
      - v[0-9]+.[0-9]+
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
      - "cargo-build-bpf"
      - "cargo-test-bpf"
      - "cargo-build-sbf"
      - "cargo-test-sbf"
      - "ci/downstream-projects/run-spl.sh"
      - ".github/workflows/downstream-project-spl.yml"
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
        default: "master"

env:
  SHELL: /bin/bash
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        program:
          - instruction-padding/program
          - token/program
          - token/program-2022
          - token/program-2022-test
          - associated-token-account/program
          - token-upgrade/program
          - feature-proposal/program
          - governance/addin-mock/program
          - governance/program
          - memo/program
          - name-service/program
          - stake-pool/program
          - stake-pool/single-pool
    steps:
      - uses: actions/checkout@v3

      - shell: bash
        run: |
          .github/scripts/purge-ubuntu-runner.sh

      - uses: mozilla-actions/sccache-action@v0.0.3

      - shell: bash
        run: |
          source ci/downstream-projects/common.sh

          git clone https://github.com/solana-labs/solana-program-library.git spl
          cp "$SOLANA_DIR"/rust-toolchain.toml spl/
          cd spl

          project_used_solana_version=$(sed -nE 's/solana-sdk = \"[>=<~]*(.*)\"/\1/p' <"token/program/Cargo.toml")
          echo "used solana version: $project_used_solana_version"
          if semverGT "$project_used_solana_version" "$SOLANA_VER"; then
            echo "skip"
            return
          fi

          ./patch.crates-io.sh "$SOLANA_DIR"

          $CARGO_BUILD_SBF
          $CARGO_TEST_SBF --manifest-path ${{ matrix.program }}/Cargo.toml
