name: Web3.js Experimental

on:
  push:
    branches: ["master"]
    paths:
      - "web3.js-experimental/**"
  pull_request:
    types: [opened, synchronize]
    paths:
      - "web3.js-experimental/**"

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web3.js-experimental

    env:
      # Configuration for Bundlewatch
      BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
      CI_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      # To use Turborepo Remote Caching, set the following environment variables for the job.
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
          cache-dependency-path: "web3.js-experimental/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
