[package]
name = "safecoin-banks-client"
version = "1.6.0"
description = "Safecoin banks client"
authors = ["Safecoin Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/safecoin"
license = "Apache-2.0"
homepage = "https://safecoin.org/"
edition = "2018"

[dependencies]
bincode = "1.3.1"
futures = "0.3"
mio = "0.7.6"
safecoin-banks-interface = { path = "../banks-interface", version = "1.6.0" }
safecoin-sdk = { path = "../sdk", version = "1.6.0" }
tarpc = { version = "0.24.1", features = ["full"] }
tokio = { version = "1.1", features = ["full"] }
tokio-serde = { version = "0.8", features = ["bincode"] }

[dev-dependencies]
safecoin-runtime = { path = "../runtime", version = "1.6.0" }
safecoin-banks-server = { path = "../banks-server", version = "1.6.0" }

[lib]
crate-type = ["lib"]
name = "safecoin_banks_client"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
