[package]
name = "solana-metrics"
description = "Solana Metrics"
documentation = "https://docs.rs/solana-metrics"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
crossbeam-channel = "0.5"
gethostname = "0.2.3"
lazy_static = "1.4.0"
log = "0.4.17"
reqwest = { version = "0.11.12", default-features = false, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
solana-sdk = { path = "../sdk", version = "=1.15.0" }

[dev-dependencies]
env_logger = "0.9.0"
rand = "0.7.0"
serial_test = "0.9.0"

[lib]
name = "solana_metrics"

[[bench]]
name = "metrics"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
